# .readthedocs.yaml
version: 2

# Build configuration
build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

# Python environment
python:
  install:
    - requirements: requirements.txt

# Documentation type
sphinx:
  builder: mkdocs

# MkDocs configuration
mkdocs:
  configuration: mkdocs.yml
